version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: >
      redis-server
      --requirepass ${REDISPASSWORD}
      --user default off
      --user ${REDISUSER} on '>${REDISPASSWORD}' allcommands allkeys
      --appendonly yes
    environment:
      - REDIS_USER=${REDISUSER}
      - REDIS_PASSWORD=${REDISPASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "-u", "${REDISUSER}", "-a", "${REDISPASSWORD}", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis-website-analyzer:
    image: redis/redis-stack-server:latest
    ports:
      - "6380:6379"
    volumes:
      - redis_data_website_analyzer:/data
    command: >
      redis-server
      --requirepass ${REDISPASSWORD_WEBSITE_ANALYZER}
      --user default off
      --user ${REDISUSER_WEBSITE_ANALYZER} on '>${REDISPASSWORD_WEBSITE_ANALYZER}' allcommands allkeys
      --appendonly yes
      --loadmodule /opt/redis-stack/lib/rejson.so
    environment:
      - REDIS_USER=${REDISUSER_WEBSITE_ANALYZER}
      - REDIS_PASSWORD=${REDISPASSWORD_WEBSITE_ANALYZER}
    healthcheck:
      test: ["CMD", "redis-cli", "-u", "${REDISUSER_WEBSITE_ANALYZER}", "-a", "${REDISPASSWORD_WEBSITE_ANALYZER}", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
  redis_data:
  redis_data_website_analyzer: 