name: "Setup and install"
description: "Common setup steps for Actions"

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22.1.0
        cache: "pnpm"

    - name: Start PostgreSQL
      uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '15'
        postgresql db: 'test_db'
        postgresql user: 'test_user'
        postgresql password: 'test_password'

    - shell: bash
      run: pnpm add -g turbo

    - shell: bash
      run: pnpm install