name: "Setup and install"
description: "Common setup steps for Actions"

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4.4.0
    - uses: actions/setup-node@v4.4.0
      with:
        node-version: 22.1.0
        cache: "pnpm"

    - name: Start PostgreSQL
      uses: harmon758/postgresql-action@v1.0.0
      with:
        postgresql version: '15'
        postgresql db: 'ritchy'
        postgresql user: 'postgres'
        postgresql password: 'postgres'
        postgresql port: '5432'
        postgresql host: 'localhost'

    - shell: bash
      run: pnpm add -g turbo

    - shell: bash
      run: pnpm install --no-frozen-lockfile