import type { DataSource, FieldMetadata } from '../types/field-metadata'

/**
 * Pre-generated schema metadata for API documentation
 * This is derived from the Zod schemas in contract.ts
 * Fields are organized hierarchically by data source
 */
export const API_SCHEMA_METADATA: FieldMetadata[] = [
  // === ROOT LEVEL FIELDS ===
  {
    path: 'success',
    name: 'success',
    type: 'boolean',
    typeLabel: 'boolean',
    isNullable: false,
    isOptional: false,
    isArray: false,
    source: 'meta',
    description: 'Indicates whether the API request was successful',
  },
  {
    path: 'data',
    name: 'data',
    type: 'object',
    typeLabel: 'object',
    isNullable: false,
    isOptional: false,
    isArray: false,
    source: 'root',
    description: 'Main enrichment data containing all company information',
    children: [
      // Quick access fields (from Google Maps)
      {
        path: 'data.googlePlaceId',
        name: 'googlePlaceId',
        type: 'string',
        typeLabel: 'string',
        isNullable: false,
        isOptional: false,
        isArray: false,
        source: 'google',
        description: 'Unique Google Place identifier',
      },
      {
        path: 'data.name',
        name: 'name',
        type: 'string',
        typeLabel: 'string | null',
        isNullable: true,
        isOptional: false,
        isArray: false,
        source: 'google',
        description: 'Business name from Google Maps',
      },
      {
        path: 'data.formattedAddress',
        name: 'formattedAddress',
        type: 'string',
        typeLabel: 'string | null',
        isNullable: true,
        isOptional: false,
        isArray: false,
        source: 'google',
        description: 'Full formatted address',
      },
      {
        path: 'data.phone',
        name: 'phone',
        type: 'string',
        typeLabel: 'string | null',
        isNullable: true,
        isOptional: false,
        isArray: false,
        source: 'google',
        description: 'International phone number',
      },
      {
        path: 'data.websiteUrl',
        name: 'websiteUrl',
        type: 'string',
        typeLabel: 'string | null',
        isNullable: true,
        isOptional: false,
        isArray: false,
        source: 'google',
        description: 'Business website URL',
      },
      {
        path: 'data.rating',
        name: 'rating',
        type: 'number',
        typeLabel: 'number | null',
        isNullable: true,
        isOptional: false,
        isArray: false,
        source: 'google',
        description: 'Google Maps rating (1-5 stars)',
      },
      {
        path: 'data.reviewCount',
        name: 'reviewCount',
        type: 'number',
        typeLabel: 'number | null',
        isNullable: true,
        isOptional: false,
        isArray: false,
        source: 'google',
        description: 'Number of Google reviews',
      },
      {
        path: 'data.location',
        name: 'location',
        type: 'object',
        typeLabel: 'object | null',
        isNullable: true,
        isOptional: false,
        isArray: false,
        source: 'google',
        description: 'Geographic coordinates (lat/lng)',
        children: [
          {
            path: 'data.location.lat',
            name: 'lat',
            type: 'number',
            typeLabel: 'number',
            isNullable: false,
            isOptional: false,
            isArray: false,
            source: 'google',
            description: 'Latitude coordinate',
          },
          {
            path: 'data.location.lng',
            name: 'lng',
            type: 'number',
            typeLabel: 'number',
            isNullable: false,
            isOptional: false,
            isArray: false,
            source: 'google',
            description: 'Longitude coordinate',
          },
        ],
      },
      {
        path: 'data.enrichmentScore',
        name: 'enrichmentScore',
        type: 'number',
        typeLabel: 'number | null',
        isNullable: true,
        isOptional: false,
        isArray: false,
        source: 'meta',
        description: 'Overall data quality score (0-100)',
      },

      // Website data
      {
        path: 'data.website',
        name: 'website',
        type: 'object',
        typeLabel: 'object | null',
        isNullable: true,
        isOptional: false,
        isArray: false,
        source: 'website',
        description: 'Data extracted from the company website',
        children: [
          {
            path: 'data.website.domain',
            name: 'domain',
            type: 'string',
            typeLabel: 'string | null',
            isNullable: true,
            isOptional: false,
            isArray: false,
            source: 'website',
            description: 'Primary domain name (e.g., "example.com")',
          },
          {
            path: 'data.website.title',
            name: 'title',
            type: 'string',
            typeLabel: 'string | null',
            isNullable: true,
            isOptional: false,
            isArray: false,
            source: 'website',
            description: 'Website page title from HTML <title> tag',
          },
          {
            path: 'data.website.description',
            name: 'description',
            type: 'string',
            typeLabel: 'string | null',
            isNullable: true,
            isOptional: false,
            isArray: false,
            source: 'website',
            description: 'Website meta description',
          },
          {
            path: 'data.website.shortDescription',
            name: 'shortDescription',
            type: 'string',
            typeLabel: 'string | null',
            isNullable: true,
            isOptional: false,
            isArray: false,
            source: 'website',
            description: 'AI-generated short description of the business',
          },
          {
            path: 'data.website.domainRegisteredAt',
            name: 'domainRegisteredAt',
            type: 'string',
            typeLabel: 'string | null',
            isNullable: true,
            isOptional: false,
            isArray: false,
            source: 'website',
            description: 'Domain registration date (ISO 8601)',
          },
          {
            path: 'data.website.emails',
            name: 'emails',
            type: 'array',
            typeLabel: 'Email[]',
            isNullable: false,
            isOptional: false,
            isArray: true,
            source: 'website',
            description: 'List of email addresses found on the website',
            children: [
              {
                path: 'data.website.emails[].email',
                name: 'email',
                type: 'string',
                typeLabel: 'string',
                isNullable: false,
                isOptional: false,
                isArray: false,
                source: 'website',
                description: 'Email address',
              },
              {
                path: 'data.website.emails[].type',
                name: 'type',
                type: 'enum',
                typeLabel: '"generic" | "role" | "personal"',
                isNullable: false,
                isOptional: false,
                isArray: false,
                source: 'website',
                description:
                  'Email classification: generic (info@), role-based (sales@), or personal',
                constraints: { enum: ['generic', 'role', 'personal'] },
              },
            ],
          },
          {
            path: 'data.website.socials',
            name: 'socials',
            type: 'object',
            typeLabel: 'object',
            isNullable: false,
            isOptional: false,
            isArray: false,
            source: 'website',
            description: 'Social media profile URLs',
            children: [
              {
                path: 'data.website.socials.linkedin',
                name: 'linkedin',
                type: 'string',
                typeLabel: 'string | null',
                isNullable: true,
                isOptional: false,
                isArray: false,
                source: 'website',
                description: 'LinkedIn company page URL',
              },
              {
                path: 'data.website.socials.facebook',
                name: 'facebook',
                type: 'string',
                typeLabel: 'string | null',
                isNullable: true,
                isOptional: false,
                isArray: false,
                source: 'website',
                description: 'Facebook page URL',
              },
              {
                path: 'data.website.socials.instagram',
                name: 'instagram',
                type: 'string',
                typeLabel: 'string | null',
                isNullable: true,
                isOptional: false,
                isArray: false,
                source: 'website',
                description: 'Instagram profile URL',
              },
            ],
          },
          {
            path: 'data.website.technologies',
            name: 'technologies',
            type: 'array',
            typeLabel: 'string[]',
            isNullable: false,
            isOptional: false,
            isArray: true,
            source: 'website',
            description:
              'Technologies detected on the website (e.g., React, Stripe, WordPress)',
          },
        ],
      },

      // Company match
      {
        path: 'data.companyMatch',
        name: 'companyMatch',
        type: 'object',
        typeLabel: 'object | null',
        isNullable: true,
        isOptional: false,
        isArray: false,
        source: 'meta',
        description: 'Confidence score and reasoning for the company match',
        children: [
          {
            path: 'data.companyMatch.confidenceScore',
            name: 'confidenceScore',
            type: 'number',
            typeLabel: 'number | null',
            isNullable: true,
            isOptional: false,
            isArray: false,
            source: 'meta',
            description:
              'Confidence score (0-100) that this is the correct company match',
          },
          {
            path: 'data.companyMatch.reasoning',
            name: 'reasoning',
            type: 'string',
            typeLabel: 'string | null',
            isNullable: true,
            isOptional: false,
            isArray: false,
            source: 'meta',
            description:
              'AI-generated explanation of why this company was matched',
          },
        ],
      },

      // Registry data (simplified - main fields)
      {
        path: 'data.registry',
        name: 'registry',
        type: 'object',
        typeLabel: 'object | null',
        isNullable: true,
        isOptional: false,
        isArray: false,
        source: 'registry',
        description: 'Official company registry data from government sources',
        children: [
          {
            path: 'data.registry.registrationNumber',
            name: 'registrationNumber',
            type: 'string',
            typeLabel: 'string',
            isNullable: false,
            isOptional: false,
            isArray: false,
            source: 'registry',
            description: 'Official company registration number',
          },
          {
            path: 'data.registry.name',
            name: 'name',
            type: 'string',
            typeLabel: 'string',
            isNullable: false,
            isOptional: false,
            isArray: false,
            source: 'registry',
            description: 'Official registered company name',
          },
          {
            path: 'data.registry.status',
            name: 'status',
            type: 'string',
            typeLabel: 'string',
            isNullable: false,
            isOptional: false,
            isArray: false,
            source: 'registry',
            description: 'Current company status (active, dissolved, etc.)',
          },
          {
            path: 'data.registry.countryCode',
            name: 'countryCode',
            type: 'string',
            typeLabel: 'string',
            isNullable: false,
            isOptional: false,
            isArray: false,
            source: 'registry',
            description: 'ISO 3166-1 alpha-2 country code',
          },
          {
            path: 'data.registry.country',
            name: 'country',
            type: 'string',
            typeLabel: 'string | null',
            isNullable: true,
            isOptional: false,
            isArray: false,
            source: 'registry',
            description: 'Country name',
          },
          {
            path: 'data.registry.tradeName',
            name: 'tradeName',
            type: 'string',
            typeLabel: 'string | null',
            isNullable: true,
            isOptional: false,
            isArray: false,
            source: 'registry',
            description: 'Trading name or doing business as (DBA)',
          },
          {
            path: 'data.registry.legalFormCode',
            name: 'legalFormCode',
            type: 'string',
            typeLabel: 'string | null',
            isNullable: true,
            isOptional: false,
            isArray: false,
            source: 'registry',
            description: 'Legal form code (e.g., LLC, SA, GmbH)',
          },
          {
            path: 'data.registry.createdAt',
            name: 'createdAt',
            type: 'string',
            typeLabel: 'string | null',
            isNullable: true,
            isOptional: false,
            isArray: false,
            source: 'registry',
            description: 'Company creation/registration date (ISO 8601)',
          },
          {
            path: 'data.registry.workforce',
            name: 'workforce',
            type: 'number',
            typeLabel: 'number | null',
            isNullable: true,
            isOptional: false,
            isArray: false,
            source: 'registry',
            description: 'Number of employees',
          },
          {
            path: 'data.registry.workforceRange',
            name: 'workforceRange',
            type: 'string',
            typeLabel: 'string | null',
            isNullable: true,
            isOptional: false,
            isArray: false,
            source: 'registry',
            description: 'Employee count range (e.g., "50-100")',
          },
          {
            path: 'data.registry.shareCapital',
            name: 'shareCapital',
            type: 'string',
            typeLabel: 'string | null',
            isNullable: true,
            isOptional: false,
            isArray: false,
            source: 'registry',
            description: 'Share capital amount',
          },
          {
            path: 'data.registry.vatNumber',
            name: 'vatNumber',
            type: 'string',
            typeLabel: 'string | null',
            isNullable: true,
            isOptional: false,
            isArray: false,
            source: 'registry',
            description: 'VAT registration number',
          },
          {
            path: 'data.registry.lei',
            name: 'lei',
            type: 'string',
            typeLabel: 'string | null',
            isNullable: true,
            isOptional: false,
            isArray: false,
            source: 'registry',
            description: 'Legal Entity Identifier (LEI) - 20-character code',
          },
          {
            path: 'data.registry.officers',
            name: 'officers',
            type: 'array',
            typeLabel: 'Officer[]',
            isNullable: false,
            isOptional: false,
            isArray: true,
            source: 'registry',
            description: 'Company directors and officers',
          },
          {
            path: 'data.registry.ubos',
            name: 'ubos',
            type: 'array',
            typeLabel: 'Ubo[]',
            isNullable: false,
            isOptional: false,
            isArray: true,
            source: 'registry',
            description: 'Ultimate Beneficial Owners (UBOs)',
          },
          {
            path: 'data.registry.financials',
            name: 'financials',
            type: 'array',
            typeLabel: 'Financial[]',
            isNullable: false,
            isOptional: false,
            isArray: true,
            source: 'registry',
            description: 'Annual financial statements',
          },
          {
            path: 'data.registry.activities',
            name: 'activities',
            type: 'array',
            typeLabel: 'Activity[]',
            isNullable: false,
            isOptional: false,
            isArray: true,
            source: 'registry',
            description:
              'Business activity codes (NACE, local classifications)',
          },
          {
            path: 'data.registry.establishments',
            name: 'establishments',
            type: 'array',
            typeLabel: 'Establishment[]',
            isNullable: false,
            isOptional: false,
            isArray: true,
            source: 'registry',
            description: 'Company establishments/branches',
          },
        ],
      },

      // Google Place (reference only)
      {
        path: 'data.googlePlace',
        name: 'googlePlace',
        type: 'object',
        typeLabel: 'object | null',
        isNullable: true,
        isOptional: false,
        isArray: false,
        source: 'google',
        description:
          'Complete Google Place data from Google Maps API (100+ fields)',
      },
    ],
  },

  // Meta object
  {
    path: 'meta',
    name: 'meta',
    type: 'object',
    typeLabel: 'object',
    isNullable: false,
    isOptional: false,
    isArray: false,
    source: 'meta',
    description: 'Request metadata and usage information',
    children: [
      {
        path: 'meta.requestId',
        name: 'requestId',
        type: 'string',
        typeLabel: 'string',
        isNullable: false,
        isOptional: false,
        isArray: false,
        source: 'meta',
        description: 'Unique identifier for this API request',
      },
      {
        path: 'meta.processingTimeMs',
        name: 'processingTimeMs',
        type: 'number',
        typeLabel: 'number',
        isNullable: false,
        isOptional: false,
        isArray: false,
        source: 'meta',
        description: 'Time taken to process the request in milliseconds',
      },
      {
        path: 'meta.creditsUsed',
        name: 'creditsUsed',
        type: 'number',
        typeLabel: 'number',
        isNullable: false,
        isOptional: false,
        isArray: false,
        source: 'meta',
        description: 'Number of credits consumed by this request',
      },
      {
        path: 'meta.creditsRemaining',
        name: 'creditsRemaining',
        type: 'number',
        typeLabel: 'number',
        isNullable: false,
        isOptional: false,
        isArray: false,
        source: 'meta',
        description: 'Remaining credits in your account',
      },
    ],
  },
]

/**
 * Get fields grouped by data source
 */
export const getFieldsBySource = (source: DataSource): FieldMetadata[] => {
  const result: FieldMetadata[] = []

  const collectBySource = (fields: FieldMetadata[]) => {
    for (const field of fields) {
      if (field.source === source) {
        result.push(field)
      }
      if (field.children) {
        collectBySource(field.children)
      }
    }
  }

  collectBySource(API_SCHEMA_METADATA)
  return result
}

/**
 * Data source labels for display
 */
export const DATA_SOURCE_LABELS: Record<DataSource, string> = {
  google: 'Google Maps',
  website: 'Website Scraping',
  registry: 'Government Registry',
  meta: 'API Metadata',
  root: 'Response',
}

/**
 * Data source descriptions
 */
export const DATA_SOURCE_DESCRIPTIONS: Record<DataSource, string> = {
  google: 'Data from Google Maps Place API',
  website: 'Data extracted from company website via web scraping',
  registry: 'Official data from government business registries',
  meta: 'Request metadata and enrichment quality scores',
  root: 'Top-level response structure',
}
