/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as AuthSearchImport } from './routes/_auth/search'
import { Route as AuthPlacesImport } from './routes/_auth/places'
import { Route as AuthListsListIdImport } from './routes/_auth/lists/$listId'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthSearchRoute = AuthSearchImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthRoute,
} as any)

const AuthPlacesRoute = AuthPlacesImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => AuthRoute,
} as any)

const AuthListsListIdRoute = AuthListsListIdImport.update({
  id: '/lists/$listId',
  path: '/lists/$listId',
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_auth/places': {
      id: '/_auth/places'
      path: '/places'
      fullPath: '/places'
      preLoaderRoute: typeof AuthPlacesImport
      parentRoute: typeof AuthImport
    }
    '/_auth/search': {
      id: '/_auth/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthSearchImport
      parentRoute: typeof AuthImport
    }
    '/_auth/lists/$listId': {
      id: '/_auth/lists/$listId'
      path: '/lists/$listId'
      fullPath: '/lists/$listId'
      preLoaderRoute: typeof AuthListsListIdImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthPlacesRoute: typeof AuthPlacesRoute
  AuthSearchRoute: typeof AuthSearchRoute
  AuthListsListIdRoute: typeof AuthListsListIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthPlacesRoute: AuthPlacesRoute,
  AuthSearchRoute: AuthSearchRoute,
  AuthListsListIdRoute: AuthListsListIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/places': typeof AuthPlacesRoute
  '/search': typeof AuthSearchRoute
  '/lists/$listId': typeof AuthListsListIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/places': typeof AuthPlacesRoute
  '/search': typeof AuthSearchRoute
  '/lists/$listId': typeof AuthListsListIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/places': typeof AuthPlacesRoute
  '/_auth/search': typeof AuthSearchRoute
  '/_auth/lists/$listId': typeof AuthListsListIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '' | '/places' | '/search' | '/lists/$listId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/places' | '/search' | '/lists/$listId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_auth/places'
    | '/_auth/search'
    | '/_auth/lists/$listId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/places",
        "/_auth/search",
        "/_auth/lists/$listId"
      ]
    },
    "/_auth/places": {
      "filePath": "_auth/places.tsx",
      "parent": "/_auth"
    },
    "/_auth/search": {
      "filePath": "_auth/search.tsx",
      "parent": "/_auth"
    },
    "/_auth/lists/$listId": {
      "filePath": "_auth/lists/$listId.tsx",
      "parent": "/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
