/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as AuthPricingImport } from './routes/_auth/pricing'
import { Route as AuthCheckoutImport } from './routes/_auth/checkout'
import { Route as AuthSearchIndexImport } from './routes/_auth/search/index'
import { Route as AuthHubspotIndexImport } from './routes/_auth/hubspot/index'
import { Route as AuthSearchSearchIdImport } from './routes/_auth/search/$searchId'
import { Route as AuthListsListIdImport } from './routes/_auth/lists/$listId'
import { Route as AuthHubspotCallbackImport } from './routes/_auth/hubspot/callback'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthPricingRoute = AuthPricingImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AuthRoute,
} as any)

const AuthCheckoutRoute = AuthCheckoutImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthRoute,
} as any)

const AuthSearchIndexRoute = AuthSearchIndexImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthHubspotIndexRoute = AuthHubspotIndexImport.update({
  id: '/hubspot/',
  path: '/hubspot/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthSearchSearchIdRoute = AuthSearchSearchIdImport.update({
  id: '/search/$searchId',
  path: '/search/$searchId',
  getParentRoute: () => AuthRoute,
} as any)

const AuthListsListIdRoute = AuthListsListIdImport.update({
  id: '/lists/$listId',
  path: '/lists/$listId',
  getParentRoute: () => AuthRoute,
} as any)

const AuthHubspotCallbackRoute = AuthHubspotCallbackImport.update({
  id: '/hubspot/callback',
  path: '/hubspot/callback',
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_auth/checkout': {
      id: '/_auth/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthCheckoutImport
      parentRoute: typeof AuthImport
    }
    '/_auth/pricing': {
      id: '/_auth/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AuthPricingImport
      parentRoute: typeof AuthImport
    }
    '/_auth/hubspot/callback': {
      id: '/_auth/hubspot/callback'
      path: '/hubspot/callback'
      fullPath: '/hubspot/callback'
      preLoaderRoute: typeof AuthHubspotCallbackImport
      parentRoute: typeof AuthImport
    }
    '/_auth/lists/$listId': {
      id: '/_auth/lists/$listId'
      path: '/lists/$listId'
      fullPath: '/lists/$listId'
      preLoaderRoute: typeof AuthListsListIdImport
      parentRoute: typeof AuthImport
    }
    '/_auth/search/$searchId': {
      id: '/_auth/search/$searchId'
      path: '/search/$searchId'
      fullPath: '/search/$searchId'
      preLoaderRoute: typeof AuthSearchSearchIdImport
      parentRoute: typeof AuthImport
    }
    '/_auth/hubspot/': {
      id: '/_auth/hubspot/'
      path: '/hubspot'
      fullPath: '/hubspot'
      preLoaderRoute: typeof AuthHubspotIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/search/': {
      id: '/_auth/search/'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthSearchIndexImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthCheckoutRoute: typeof AuthCheckoutRoute
  AuthPricingRoute: typeof AuthPricingRoute
  AuthHubspotCallbackRoute: typeof AuthHubspotCallbackRoute
  AuthListsListIdRoute: typeof AuthListsListIdRoute
  AuthSearchSearchIdRoute: typeof AuthSearchSearchIdRoute
  AuthHubspotIndexRoute: typeof AuthHubspotIndexRoute
  AuthSearchIndexRoute: typeof AuthSearchIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCheckoutRoute: AuthCheckoutRoute,
  AuthPricingRoute: AuthPricingRoute,
  AuthHubspotCallbackRoute: AuthHubspotCallbackRoute,
  AuthListsListIdRoute: AuthListsListIdRoute,
  AuthSearchSearchIdRoute: AuthSearchSearchIdRoute,
  AuthHubspotIndexRoute: AuthHubspotIndexRoute,
  AuthSearchIndexRoute: AuthSearchIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/checkout': typeof AuthCheckoutRoute
  '/pricing': typeof AuthPricingRoute
  '/hubspot/callback': typeof AuthHubspotCallbackRoute
  '/lists/$listId': typeof AuthListsListIdRoute
  '/search/$searchId': typeof AuthSearchSearchIdRoute
  '/hubspot': typeof AuthHubspotIndexRoute
  '/search': typeof AuthSearchIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/checkout': typeof AuthCheckoutRoute
  '/pricing': typeof AuthPricingRoute
  '/hubspot/callback': typeof AuthHubspotCallbackRoute
  '/lists/$listId': typeof AuthListsListIdRoute
  '/search/$searchId': typeof AuthSearchSearchIdRoute
  '/hubspot': typeof AuthHubspotIndexRoute
  '/search': typeof AuthSearchIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/checkout': typeof AuthCheckoutRoute
  '/_auth/pricing': typeof AuthPricingRoute
  '/_auth/hubspot/callback': typeof AuthHubspotCallbackRoute
  '/_auth/lists/$listId': typeof AuthListsListIdRoute
  '/_auth/search/$searchId': typeof AuthSearchSearchIdRoute
  '/_auth/hubspot/': typeof AuthHubspotIndexRoute
  '/_auth/search/': typeof AuthSearchIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/checkout'
    | '/pricing'
    | '/hubspot/callback'
    | '/lists/$listId'
    | '/search/$searchId'
    | '/hubspot'
    | '/search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/checkout'
    | '/pricing'
    | '/hubspot/callback'
    | '/lists/$listId'
    | '/search/$searchId'
    | '/hubspot'
    | '/search'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_auth/checkout'
    | '/_auth/pricing'
    | '/_auth/hubspot/callback'
    | '/_auth/lists/$listId'
    | '/_auth/search/$searchId'
    | '/_auth/hubspot/'
    | '/_auth/search/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/checkout",
        "/_auth/pricing",
        "/_auth/hubspot/callback",
        "/_auth/lists/$listId",
        "/_auth/search/$searchId",
        "/_auth/hubspot/",
        "/_auth/search/"
      ]
    },
    "/_auth/checkout": {
      "filePath": "_auth/checkout.tsx",
      "parent": "/_auth"
    },
    "/_auth/pricing": {
      "filePath": "_auth/pricing.tsx",
      "parent": "/_auth"
    },
    "/_auth/hubspot/callback": {
      "filePath": "_auth/hubspot/callback.tsx",
      "parent": "/_auth"
    },
    "/_auth/lists/$listId": {
      "filePath": "_auth/lists/$listId.tsx",
      "parent": "/_auth"
    },
    "/_auth/search/$searchId": {
      "filePath": "_auth/search/$searchId.tsx",
      "parent": "/_auth"
    },
    "/_auth/hubspot/": {
      "filePath": "_auth/hubspot/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/search/": {
      "filePath": "_auth/search/index.tsx",
      "parent": "/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
